networks:
  monitoring_internal:
    external: true

services:
  school-lunch-schedule:
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data/
        target: /data/
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
        read_only: true
    ports:
      - "8080:8080"
    networks:
      - monitoring_internal
